query sectors($limit: Int, $offset: Int, $filter: basic_sectors_bool_exp) {
  sectors: basic_sectors(limit: $limit, offset: $offset, where: $filter) {
    id
    name
    description
    active_jobs {
      count
    }
  }
}
